---
- name: Playbook for rebooting the RPis
  hosts: pi-cluster
  gather_facts: no
  tasks:
    - name: 'Reboot all nodes'
      shell: shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true
      become: true

    - pause: seconds=10

    # Now we will run a local 'ansible -m ping' on this host until it returns.
    # This works with the existing ansible hosts inventory and so any custom ansible_ssh_hosts definitions are being used
    - local_action: shell ansible all -m ping
      register: result
      until: result.rc == 0
      retries: 30
      delay: 10

    # And finally, execute 'uptime' when the host is back.
    - shell: uptime
