---
- name: Playbook for rebooting the RPis
  hosts: pi-cluster
  gather_facts: no
  tasks:
    - name: Reboot system
      shell: sleep 2 && shutdown -r now "Ansible triggered reboot"
      async: 1
      poll: 0
      ignore_errors: true
      become: true

    - name: Wait for system to boot up
      local_action: wait_for host={{ ansible_host }} port={{ ansible_port }} state=started delay=15 timeout=300
      become: false

    - debug:
        msg: "We're back again. Running on {{ inventory_hostname }}"
