---
- name: Playbook for rebooting the RPis
  hosts: pi-cluster
  gather_facts: no
  tasks:
    - name: Reboot all nodes
      shell: sleep 5 && shutdown -r now
      ignore_errors: true
      become: true

    - name: Wait for server to come back
      local_action: wait_for host = {{ ansible_default_ipv4.address }} port=22 state=started delay=30 timeout=300 state=started
      become: false
      ignore_errors: true
