---
- name: Delete Repositories
  hosts: pi-cluster
  tasks:
  - name: remove dispy
    become: yes
    command: rm -R /home/pi/dispy
  - name: remove prowler
    become: yes
    command: rm -R /home/pi/prowler