---
- import_playbook: wifi_sutd.yml

- name: Playbook for setting up a new worker node
  hosts: pi-cluster
  tasks:
  - name: Expand filesystem to fill disk
    command: raspi-config --expand-rootfs
    become: yes
  - name: Install system packages
    become: yes
    apt: name=htop state=present
  - apt: name=nmap state=present
    become: yes
  - apt: name=git state=present
    become: yes
  - name: Install python3-dev
    become: yes
    apt:
      name: python3-dev
      state: present
  - name: Install python3-pip
    become: yes
    apt:
      name: python3-pip
      state: present
  - name: Install python3-numpy
    become: yes
    apt:
      name: python3-numpy
      state: present
  - name: Clone tlkh/prowler
    command: git clone https://github.com/tlkh/prowler.git
  - name: Upgrade pip and setuptools
    become: yes
    pip:
      requirements: ~/prowler/playbooks/files/pip-upgrade.txt
      extra_args: --upgrade
      executable: pip3
  - name: Configure Python packages
    become: yes
    pip:
      executable: pip3
      requirements: ~/prowler/requirements.txt

- import_playbook: wifi_testnet.yml

- import_playbook: upgrade.yml

- import_playbook: reboot.yml
