---
- import_playbook: wifi_sutd.yml
- import_playbook: rpi3_internet.yml
- import_playbook: reboot.yml

- name: Playbook for setting up a new worker node
  hosts: pi-cluster
  tasks:
  - name: Expand filesystem to fill disk
    command: raspi-config --expand-rootfs
    become: yes
  - name: Install system packages
    become: yes
    apt: name={{item}} state=installed
    with_items:
      - nmap
      - htop
      - git
  - name: Install python3 packages
    become: yes
    apt: name={{item}} state=installed
    with_items:
      - python3-dev
      - python3-pip
      - python3-numpy
      - python-dev
      - python-pip
  - name: Upgrade pip and setuptools
    become: yes
    pip:
      requirements: /home/pi/prowler/playbooks/files/pip-upgrade.txt
      extra_args: --upgrade
      executable: pip3
  - name: Configure Python packages
    become: yes
    pip:
      executable: pip3
      requirements: /home/pi/prowler/requirements.txt

- import_playbook: wifi_testnet.yml

- import_playbook: upgrade.yml

- import_playbook: rpi3_isolate.yml

- import_playbook: reboot.yml
