---
- name: Playbook for shutting down cluster nodes
  hosts: pi-cluster
  gather_facts: no
  tasks:
    - name: 'Shutdown RPi'
      shell: shutdown -h now
      async: 0
      poll: 0
      ignore_errors: true
      become: true