---
- name: Connect node to TestingNet
  hosts: pi-cluster 
  tasks:
  - name: copy wpa_supplicant file (TestingNet)
    become: yes
    template:
      src=: files/wpa_testnet.conf
      dest: /etc/wpa_supplicant/wpa_supplicant.conf
