---
- name: Connect node to SUTD_Student
  hosts: pi-cluster
  tasks:
  - name: copy wpa_supplicant file (SUTD_Student)
    become: yes
    template:
      src: files/wpa_sutd.conf
      dest: /etc/wpa_supplicant/wpa_supplicant.conf
